name: Deploy VSCode Extension

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run compile

      - name: Bundle with webpack
        run: npm run webpack

      - name: Package extension
        run: npx @vscode/vsce package

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        if: startsWith(github.ref, 'refs/tags/v')

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Prompt Enhancer ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: "*.vsix"
          body: |
            # Prompt Enhancer ${{ github.ref_name }} - Initial Release

            ![logo](https://github.com/user-attachments/assets/90e3876f-8341-4f12-aa8d-84b6ee0ac710)

            ## Overview
            Prompt Enhancer is a VS Code extension that leverages AI models to improve your text prompts. It transforms basic instructions into detailed, well-structured prompts that generate better results from AI assistants.

            ## Features
            - One-click prompt enhancement via command palette or editor title button
            - Support for multiple AI models (OpenAI, Claude, Deepseek, Azure OpenAI)
            - Customizable enhancement instructions to fit your specific needs
            - Keyboard shortcut (Alt+E) for quick access

            ## Setup
            1. Configure your preferred AI model in settings
            2. Add your API key(s) for the selected model
            3. Customize enhancement instructions (optional)

            ## Usage
            - Select text in the editor
            - Click the enhancement icon or use Alt+E
            - Wait for the enhanced result to appear

            ## Requirements
            - VS Code 1.80.0 or higher
            - Internet connection
            - API key for at least one supported AI model

            Thank you for trying Prompt Enhancer! Feedback and contributions are welcome.
        env:
          GITHUB_TOKEN: ${{ secrets.PROMPT_ENHANCER_PAT }}

      - name: Publish to Visual Studio Marketplace
        run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}